name: Update Version Badge on Pull

on:
  pull_request:
    types: [closed] # Dispara ao fechar um pull request.

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update version JSON
      run: |
        mkdir -p docs
        echo '{
          "schemaVersion": 1,
          "label": "version",
          "message": "1.0.0", # Você pode substituir pela versão real.
          "color": "blue"
        }' > docs/version.json

    - name: Commit and push updated version badge
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add docs/version.json
        git commit -m "Update version badge"
        git push
